### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by tanpengsccd** [jackma778/sh#1]
把 docker-compose.yml 改为 
```
version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v4.26.0
    # container_name: v2ray
    restart: always
    ports:
      - "${runPort}:${runPort}"
    command: "v2ray -config=${api}/api/vmess_server_config/${nodeId}/?token=${token}"

  v2scar:
    # container_name: v2scar
    image: debian:10
    restart: always
    depends_on:
      - v2ray
    links:
      - v2ray
    volumes:
      - ./:/root
    command: sh -c "apt update -y && apt install ca-certificates -y && chmod +x /root/v2scar && /root/v2scar -id=${nodeId} -gp=v2ray:8079" 

```

有的小鸡,本身就就接了其它机场地址,再接现在的MJJ, container_name会同名无法启动. volume 使用相对路径 更灵活.
